### ISSUE TITLE
Relays area to be backwards from code

### ISSUE THREAD

**Issue by arhyneRWU** [ControlEverythingCom/NCD8Relay#1]
When I turn relay 1 on, NO circuit associated with 1 on the board does not close.  

Board is stamped 1-----4  and 5-----8

relayController.turnOnRelay(1) appears to operate number 8 on the board.  
likewise
relayController.turnOnRelay(8) operates number 1 on the board.

**Comment by telliottosceola** [comment]
Can you tell me the part number of the controller you have?  We have a few different 8 channel boards which all use this same Library.  I suspect the labeling on the board is backwards but would like to confirm this.

**Comment by arhyneRWU** [comment]
MCP23008_SCR8G5LE

**Comment by telliottosceola** [comment]
I have a MCP23008_SCR8G5LE here at my desk running this code in the loop:

void loop()
{
    relayController.turnOnRelay(1);
    delay(1000);
    relayController.turnOffRelay(1);
    delay(1000);
}

It is turning relay 1 on and off once per second.

**Comment by telliottosceola** [comment]
My apologies.

I was watching the LEDs but did not actually use a meter to make sure the correct relay was switching.  The physical relays on the board are labeled backwards so R1 is actually R8 as you stated.  We will correct this on our next revision.  Thank you very much for pointing this out.

**Comment by arhyneRWU** [comment]
No worries.  These are really nice devices. Hope they take off and you make more interesting I2C gear with high quality parts.

**Comment by arhyneRWU** [comment]
Also, anyway for me to program the NCD8Relay.cpp library to reverse it?  If not I'll write variables to make 1 = 8, this way if someone opens the box and tries to trouble shoot something they are turning 1 on and not 8.

**Comment by telliottosceola** [comment]
Hi,

My first thought was to patch the firmware to reverse the commands to the correct relay but then the on board LEDs would be wrong so I am in a dilemma with that.  What do you think?

**Comment by arhyneRWU** [comment]
How about I print a sticker and re number my board.

**Comment by telliottosceola** [comment]
Funny,  That is the same solution we came up with :)
