### ISSUE TITLE
in Time_Activated_Relay example, multiple events not properly loaded into internal event array

### ISSUE THREAD

**Issue by trackdork** [ControlEverythingCom/NCD8Relay#2]
when submitting multiple strings via "timeEventsDevice1", the string is correctly parsed and written to memory, however when subsequently loading those events into the "eventArray" storage, there is a memory access bug in "readStoredEvents" whereby the second dimensional index variable grows too large.

My fix, change lines 117-118 as follows:

original:
```
116             for(int i = startIndex; i < startIndex+36; i+=4){
117	            EEPROM.get(i, eventArray[eventIndex][(i-1)/4]);
118	            Serial.printf("%i, ", eventArray[eventIndex][(i-1)/4]);
119	        }
```

fixed:
```
116             for(int i = startIndex; i < startIndex+36; i+=4){
117	            int arrayIndex = ((i-1)/4) % 9;
118	            EEPROM.get(i, eventArray[eventIndex][arrayIndex]);
119	            Serial.printf("%i, ", eventArray[eventIndex][arrayIndex]);
120	        }
```

**Comment by telliottosceola** [comment]
Hi,

Thank you very much for contributing.  Would you be willing to submit a pull request for this fix?  I would like for you to have credit for the bug fix.

Thank you,
Travis Elliott

**Comment by trackdork** [comment]
Happy to help... long time programmer, but first git commit.  First time for everything!  ;)
